# Компʼютерний практикум №2
Виконав студент групи ЗК-41мп Гломозда Костянтин

ОСНОВИ РОБОТИ З БІБЛІОТЕКОЮ NUMPY

In [21]:
! pip install numpy --quiet

1) Створіть 1D масив чисел від 0 до 9

Можна використати np.linspace(0, 9, 10).

In [2]:
import numpy as np
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2) Створіть 3×3 numpy масив, що складається з усіх True

Можна використати np.full((3,3), True).

In [3]:
true_array = np.ones((3, 3), dtype=bool)
true_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3) Отримайте всі непарні числа з масиву

Можна використати np.extract(arr % 2 == 1, arr).

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]
odd_numbers

array([1, 3, 5, 7, 9])

4) Треба замінити всі непарні числа на -1

Можна використати np.where(arr % 2 == 1, -1, arr).

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

5) Треба замінити всі непарні числа на -1 не змінюючи масив

Можна використати arr.copy() для копіювання перед модифікацією.

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr = np.where(arr % 2 == 1, -1, arr)
new_arr, arr

(array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

6) Перетворіть 1D масив у 2D масив з 2 рядками

Можна використати np.resize(arr, (2, 5)).

In [7]:
arr = np.arange(10)
reshaped_arr = arr.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

7) Складіть вертикально масиви a та b

Можна використати np.concatenate((a, b), axis=0).

In [8]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
vstacked = np.vstack((a, b))
vstacked

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

8) Складіть горизонтально два масиви

Можна використати np.concatenate((a, b), axis=1).

In [9]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
hstacked = np.hstack((a, b))
hstacked

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

9) Зробіть наступний патерн не використовуючи жорстке прописування коду

Можна використати np.concatenate([np.repeat(a, 3), np.tile(a, 3)]).

In [10]:
a = np.array([1, 2, 3])
pattern = np.r_[np.repeat(a, 3), np.tile(a, 3)]
pattern

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

10) Отримайте однакові значення між масивами a та b

Можна використати np.setxor1d(a, b) для виявлення спільних елементів.

In [11]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
intersection = np.intersect1d(a, b)
intersection

array([2, 4])

11) Видаліть значення масиву a, які є у масиві b

Можна використати np.in1d(a, b) для виявлення унікальних елементів.

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
difference = np.setdiff1d(a, b)
difference

array([1, 2, 3, 4])

12) Отримайте індекси елементів які співпадають у двох масивах

Можна використати np.nonzero(a == b).

In [13]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
matching_indices = np.where(a == b)
matching_indices

(array([1, 3, 5, 7]),)

13) Отримайте всі значення які більші за 5 та менші або рівні 10

Можна використати np.compress((a > 5) & (a <= 10), a).

In [14]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
filtered_values = a[np.logical_and(a > 5, a <= 10)]
filtered_values

array([ 6,  9, 10])

14) Перетворіть функцію maxx так, щоб вона могла працювати з масивами

Можна використати np.maximum(a, b) для порівняння масивів.

In [15]:
def maxx(x, y):
    return x if x >= y else y

pair_max = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
result


array([6, 7, 9, 8, 9, 7, 5])

15) Поміняйте місцями колонку 1 та 2

Можна використати np.take(arr, [1, 0, 2], axis=1).

In [16]:
arr = np.arange(9).reshape(3, 3)
swapped_arr = arr[:, [1, 0, 2]]
swapped_arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

16) Створіть 2D масив розміром 5x3, який складається з довільних десяткових чисел у діапазоні між 5 та 10

Можна використати np.random.uniform(5, 10, (5, 3)).

In [17]:
random_array = 5 + (10 - 5) * np.random.rand(5, 3)
random_array

array([[7.44339589, 8.38838699, 6.73498298],
       [8.56611732, 7.62924811, 8.03529114],
       [5.2074398 , 6.58224295, 7.41568567],
       [6.91333994, 8.92274857, 6.9167841 ],
       [8.10162224, 7.47057487, 5.11338364]])

17) Як виводити тільки 3 знаки після коми в масиві numpy

Можна використати np.around(rand_arr, decimals=3).

In [18]:
np.set_printoptions(precision=3)
rand_arr = np.random.random((5, 3))
rand_arr

array([[0.693, 0.835, 0.956],
       [0.191, 0.628, 0.597],
       [0.274, 0.55 , 0.253],
       [0.547, 0.459, 0.025],
       [0.606, 0.831, 0.716]])

18) Як друкувати масив змінивши наукову нотацію на інженерну

Можна використати "{:.6f}".format() для форматування вручну.

In [19]:
np.set_printoptions(suppress=True, precision=6)
rand_arr = np.random.seed(100)
rand_arr = np.random.random([3, 3]) / 1e3
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

19) Як надрукувати весь масив numpy без обрізання значень

Можна використати np.set_printoptions(edgeitems=len(a)).

In [20]:
np.set_printoptions(threshold=np.inf)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

20) Імпортуйте датасет iris зберігаючи текст неушкодженим

Можна використати pd.read_csv(url) з pandas для імпорту.

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

21) Отримайте текст з колонки species

Можна використати np.array(iris_1d)[:, 4] для доступу до стовпця.

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='utf-8')
species = [row[4] for row in iris_1d]
species

[np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),
 np.str_('Iris-setosa'),


22) Змініть 1D iris на 2D масив, опустивши текстове поле species

Можна використати np.delete(iris_1d, 4, axis=1) для видалення стовпця.

In [25]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d], dtype='float')
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

23) Знайдіть mean, median, standard deviation першої колонки sepallength

Можна використати scipy.stats.describe(iris) для розширеного опису.

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean = np.mean(iris)
median = np.median(iris)
std_dev = np.std(iris)
mean, median, std_dev

(np.float64(5.843333333333334),
 np.float64(5.8),
 np.float64(0.8253012917851409))

24) Створіть нормалізовану форму з sepallength із значеннями між 0 та 1

Можна використати MinMaxScaler з sklearn.preprocessing.

In [27]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
normalized_sepallength = (sepallength - np.min(sepallength)) / np.ptp(sepallength)
normalized_sepallength

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

25) Розрахуйте 5-ий та 95-ий перцентилі sepallength

Можна використати scipy.stats.scoreatpercentile.

In [28]:
percentile_5 = np.percentile(sepallength, 5)
percentile_95 = np.percentile(sepallength, 95)
percentile_5, percentile_95

(np.float64(4.6), np.float64(7.254999999999998))

26) Знайдіть позиції пропущених значень в першій колонці sepallength

Можна використати np.argwhere(np.isnan(iris_2d[:, 0])).

In [29]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
missing_positions = np.where(np.isnan(iris_2d[:, 0]))
missing_positions

(array([67, 93]),)

27) Виберіть рядки iris_2d датасету, які не мають nan значень

Можна використати np.isfinite(iris_2d) для аналогічної фільтрації.

In [30]:
non_nan_rows = iris_2d[~np.isnan(iris_2d).any(axis=1)]
non_nan_rows

array([], shape=(0, 5), dtype=float64)

28) Знайдіть кореляцію між SepalLength та PetalLength

Можна використати scipy.stats.pearsonr.

In [31]:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]
correlation = np.corrcoef(sepal_length, petal_length)[0, 1]
correlation

np.float64(nan)

29) Розрахуйте евклідову відстань між двома масивами

Можна використати scipy.spatial.distance.euclidean(a, b).

In [32]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
euclidean_distance = np.linalg.norm(a - b)
euclidean_distance

np.float64(6.708203932499369)

30) Знайдіть всі піки в 1D масиві

Можна використати scipy.signal.find_peaks(a) для виявлення піків.

In [33]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
diff = np.diff(a)
peaks = np.where((np.sign(diff[:-1]) > 0) & (np.sign(diff[1:]) < 0))[0] + 1
peaks

array([2, 5])