# Компʼютерний практикум №4
Виконав студент групи ЗК-41мп Гломозда Костянтин

ОСНОВИ РОБОТИ З БІБЛІОТЕКОЮ PYTORCH

Встановлення бібліотеки

In [28]:
! pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124 --quiet

Використання GPU

In [29]:
import torch


torch.cuda.is_available()

True

In [30]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

1) Створіть із списку list(range(9)) тензор. Передбачте та перевірте, який розмір, зсув та кроки він має.

In [31]:
import torch
a = torch.tensor(list(range(9)), device=device)

a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

2) Створіть тензор b = a.view(3, 3). Яке значення має b[1,1]?

In [32]:
b = a.view(3, 3)

b[1, 1]

tensor(4, device='cuda:0')

3) Створіть тензор c = b[1:,1:]. Передбачте та перевірте, який розмір, зсув та кроки він має.

In [33]:
c = b[1:, 1:]
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

4) Виберіть математичну операцію, таку як косинус або квадратний корінь. Чи можете ви знайти відповідну функцію в бібліотеці torch?

In [34]:
cosine_result = torch.cos(a.float())
sqrt_result = torch.sqrt(a)

sqrt_result, cosine_result

(tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
        device='cuda:0'),
 tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
         -0.1455], device='cuda:0'))

5) Чи існує версія вашої функції, яка працює in-place?

In [35]:
a.cos_()

a

RuntimeError: result type Float can't be cast to the desired output type Long

Потрібно перетворити tensor на float

In [36]:
a = a.float()
a.cos_()

a

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455], device='cuda:0')