# Компʼютерний практикум №5
Виконав студент групи ЗК-41мп Гломозда Костянтин

ГРАДІЄНТНИЙ СПУСК

Завдання: 1. Натренуйте модель лінійної регресії надану в теоретичному описі
(для аналізу врожайністі яблук та апельсинів) деяку кількість епох.
Подивіться як змінюються ваги та похибка (втрати). Знайдіть оптимальну
кількість епох для тренування. Порахуйте MSE та зробіть висновки щодо
оптимальної кількості епох та отриманих результатів.

Ініціалізація відеокарти

In [2]:
import torch


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

1) Ініціалізація вхідних та цільових даних

In [7]:
import numpy as np


inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

inputs = torch.from_numpy(inputs).to(device)
targets = torch.from_numpy(targets).to(device)

2) Ініціалізація моделі та ваг

In [8]:
w = torch.randn(2, 3, requires_grad=True, device=device)
b = torch.randn(2, requires_grad=True, device=device)

def model(x):
    return x @ w.t() + b

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

3) Навчання моделі лінійної регресії протягом кількох епох

In [10]:
learning_rate = 1e-5
epochs = 10

for epoch in range(epochs):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()

    with torch.no_grad():
        w -= w.grad * learning_rate
        b -= b.grad * learning_rate
        print(w)
        print(b)
        w.grad.zero_()
        b.grad.zero_()

tensor([[ 0.6179, -0.8250,  1.4747],
        [ 0.1417,  0.9178,  0.0532]], device='cuda:0', requires_grad=True)
tensor([ 1.1883, -0.5953], device='cuda:0', requires_grad=True)
tensor([[ 0.6263, -0.7991,  1.4858],
        [ 0.1399,  0.9188,  0.0540]], device='cuda:0', requires_grad=True)
tensor([ 1.1884, -0.5953], device='cuda:0', requires_grad=True)
tensor([[ 0.6317, -0.7765,  1.4949],
        [ 0.1382,  0.9197,  0.0549]], device='cuda:0', requires_grad=True)
tensor([ 1.1885, -0.5953], device='cuda:0', requires_grad=True)
tensor([[ 0.6348, -0.7566,  1.5023],
        [ 0.1364,  0.9206,  0.0558]], device='cuda:0', requires_grad=True)
tensor([ 1.1886, -0.5953], device='cuda:0', requires_grad=True)
tensor([[ 0.6358, -0.7389,  1.5084],
        [ 0.1347,  0.9215,  0.0567]], device='cuda:0', requires_grad=True)
tensor([ 1.1887, -0.5953], device='cuda:0', requires_grad=True)
tensor([[ 0.6353, -0.7231,  1.5134],
        [ 0.1330,  0.9225,  0.0576]], device='cuda:0', requires_grad=True)
tensor([

4) Оцінка похибки (MSE) після тренування моделі з використанням CUDA

In [13]:
preds = model(inputs)
final_loss = mse(preds, targets)

final_loss

tensor(1049.8235, device='cuda:0', grad_fn=<DivBackward0>)